version: "3.8"

services:
    db:
        image: mysql:8.0
        container_name: ${CONTAINER_DB}
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    adminer:
        image: adminer:latest
        container_name: ${CONTAINER_ADMINER}
        restart: unless-stopped
        ports:
            - "${ADMINER_PORT}:8080"
        depends_on:
            - db

    server:
        build:
            context: .
            dockerfile: ./apps/server/Dockerfile
            args:
                SERVER_PORT: ${SERVER_PORT}
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        container_name: ${CONTAINER_SERVER}
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - ./apps/server/src:/app/apps/server/src
            - ./packages/shared/src:/app/packages/shared/src
            - /app/node_modules
        depends_on:
            - db

    web:
        build:
            context: .
            dockerfile: ./apps/web/Dockerfile
            args:
                WEB_PORT: ${WEB_PORT}
        ports:
            - "${WEB_PORT}:${WEB_PORT}"
        container_name: ${CONTAINER_WEB}
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - ./apps/web/src:/app/apps/web/src
            - ./packages/shared/src:/app/packages/shared/src
            - /app/node_modules
        depends_on:
            - db

volumes:
    mysql_data:
